# Generated by Django 2.2.1 on 2019-05-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('size', models.SmallIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')], default=0, verbose_name='Size')),
                ('solo_point', models.BooleanField(default=True, verbose_name='Point for one person')),
                ('status', models.SmallIntegerField(choices=[(0, 'Preparing'), (1, 'Not cleaned'), (2, 'In cleaning'), (3, 'Cleaned, not taken out'), (4, 'Taking out'), (5, 'Complete')], verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChanging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Preparing'), (1, 'Not cleaned'), (2, 'In cleaning'), (3, 'Cleaned, not taken out'), (4, 'Taking out'), (5, 'Complete')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garbage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='garbage.Garbage')),
            ],
        ),
        migrations.CreateModel(
            name='GarbageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=300, verbose_name='Link on photo')),
                ('garbage_status', models.SmallIntegerField(choices=[(0, 'Preparing'), (1, 'Not cleaned'), (2, 'In cleaning'), (3, 'Cleaned, not taken out'), (4, 'Taking out'), (5, 'Complete')], verbose_name='Status')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garbage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='garbage.Garbage')),
            ],
        ),
        migrations.CreateModel(
            name='GarbageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('garbage_status', models.SmallIntegerField(choices=[(0, 'Preparing'), (1, 'Not cleaned'), (2, 'In cleaning'), (3, 'Cleaned, not taken out'), (4, 'Taking out'), (5, 'Complete')], verbose_name='Status')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garbage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='garbage.Garbage')),
            ],
        ),
    ]
