# Generated by Django 2.2.1 on 2019-06-16 17:55

from django.db import migrations, models
import django.db.models.deletion
import garbage.models


def delete_old_images(apps, schema_editor):
    GarbageImage = apps.get_model("garbage", "GarbageImage")
    GarbageImage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('garbage', '0002_auto_20190610_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=garbage.models.upload_image_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(delete_old_images),
        migrations.AlterField(
            model_name='garbageimage',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garbage.MediaObject'),
        ),
    ]
